### ISSUE TITLE
compile error in examples/compare_all_models.py

### ISSUE THREAD

**Issue by SungmanHong** [yzhao062/pyod#195]
I just download your code and
run examples/compare_all_models.py

but it has compile error as belows..
I think it may be a error? 

----------------
12 fitting Locally Selective Combination (LSCP)
Traceback (most recent call last):
  File "C:/Users/owner/Downloads/pyod-master/pyod-master/examples/compare_all_models.py", line 140, in <module>
    scores_pred = clf.decision_function(X) * -1
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\site-packages\pyod\models\lscp.py", line 212, in decision_function
    decision_scores = self._get_decision_scores(X)
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\site-packages\pyod\models\lscp.py", line 273, in _get_decision_scores
    local_pseudo_ground_truth, local_train_scores[:, d])[0]
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\stats\stats.py", line 3501, in pearsonr
    raise ValueError('x and y must have length at least 2.')
ValueError: x and y must have length at least 2.

Process finished with exit code 1

**Comment by SungmanHong** [comment]
I think

https://github.com/yzhao062/pyod/issues/194

maybe related to this. thx.
